### ISSUE TITLE
feat: provide koa support

### ISSUE THREAD

**Issue by xmlking** [typestack/socket-controllers#1]
please provide koa2 support similar to routing-controllers

**Comment by pleerock** [comment]
Go ahead and try do it on your own. I'm pretty busy with other libs at the moment

**Comment by xmlking** [comment]
will try next week and send PR if I got it correct. 
Thanks

**Comment by Extarys** [comment]
Any update on how to use this with routing-controllers?

Btw, good job with both projects ;)

**Comment by rustamwin** [comment]
Hi @xmlking 
This project don't necessary to support any framework
