### ISSUE TITLE
How to use SocketIO() without OnMessage

### ISSUE THREAD

**Issue by ayonsaha2011** [typestack/socket-controllers#11]
can we use socket broadcast to room without OnMessage i need to broadcast a emit on post save use like notification

**Comment by rustamwin** [comment]
can you explain more?

**Comment by ikit** [comment]
I think I have a similar need.
My server is running long tasks (pipeline) and I want to inform all clients of the progress of these pipelines ... 
So the question is: How to send a message to all clients connected to the server from a server-side event ?

**Comment by gabheadz** [comment]
Same need here. Basically actual functionality is great for a request-response model. But in @ikit scenario there should be a way for the backend to send messages on a discretional basis.

**Comment by gottipatibalu** [comment]
> I think I have a similar need.
> My server is running some tasks and I want to inform all clients of the progress of these tasks...
> So the question is: How to send a message to all connected clients connected from a server-side event ?

Did you find any way to achieve this?

**Comment by rustamwin** [comment]
How about this:
```js
const app = require("express")();
const server = require("http").Server(app);
const io = require("socket.io")(server);
app.io = io;

server.listen(3001);

app.get("/", function (req: any, res: any) {
    req.app.io.broadcast.emit('hello', 'Hello everyone');
});

useSocketServer(io);
```

**Comment by gottipatibalu** [comment]
> How about this:
> 
> ```js
> const app = require("express")();
> const server = require("http").Server(app);
> const io = require("socket.io")(server);
> app.io = io;
> 
> server.listen(3001);
> 
> app.get("/", function (req: any, res: any) {
>     req.app.io.broadcast.emit('hello', 'Hello everyone');
> });
> 
> useSocketServer(io);
> ```

Thank you. I am kind of using like this as a workaround. Just wondering if there is a right way to do it.

**Comment by rustamwin** [comment]
So far this is a temporary solution.

**Comment by gottipatibalu** [comment]
Sure Thank you. I created a decorator to hide that logic and accessing it in my routes.

 @Get('/checkStatus')
    public async checkStatus(@socket() socketIo: Server) {
          socketIo.emit('hello', 'Hello everyone');
    }

**Comment by stingers** [comment]
hello, @gottipatibalu,
> Sure Thank you. I created a decorator to hide that logic and accessing it in my routes.

it possible to share  or explain how to do that.
Thanks

**Comment by gottipatibalu** [comment]
Set socket object on express object like described above and use below decorator to access it from the route
Here is the decorator decorator I created.

```js
 export function socket(options?: { required?: boolean }) {
    return createParamDecorator({
        required: options && options.required ? true : false,
        value: (action) => {
            if (action.request.app) {
                return action.request.app.get('socketio');
            }
            return undefined;
        }
    });
}
```
Route Example

```js
 @Get('/checkStatus')
    public async checkStatus(@socket() socketIo: Server) {
          socketIo.emit('hello', 'Hello everyone');
    }
```


I am using routing-controllers to define my routes

**Comment by gentritabazi01** [comment]
Can we use here decorator: `SocketIO()` ?
