### ISSUE TITLE
middlewareDirs does not exists in  SocketControllersOptions 

### ISSUE THREAD

**Issue by geomen888** [typestack/socket-controllers#13]
1. It's not workable 
import "reflect-metadata";
import {createSocketServer, loadControllers} from "socket-controllers";
let io = createSocketServer(3000, {
    controllers: [__dirname + "/controllers/**/*.js"],
    middlewareDirs: [__dirname + "/middlewares/**/*.js"]
});
2. workable only this

import "src/sockets/middlewares/clients/ClientAuthMiddleware"; 
 createSocketServer(3000, {
    controllers: [__dirname + "/sockets/controllers/clients/*{.js,.ts}"],
   // middlewareDirs: [__dirname + "/sockets/middlewares/*{.js,.ts}"]
});

But I need variant 1. to be workable (I need  middleware inside block not out of,  maybe acceptable global import, then inside => dir selector between instances  by middlewareDirs )
Thank U.

**Comment by NoNameProvided** [comment]
Closed in #17
