### ISSUE TITLE
question: Can't get it to work correctly

### ISSUE THREAD

**Issue by nickojs** [typestack/socket-controllers#156]
**I was trying to...**
implement socket communication between my existing backend and a React application. The backend is powered by routing-controllers, so I decided to use this lib to follow a standard. But I can't make it work correctly. I'm not sure what I'm doing wrong :cry: 

**The problem:**
It looks like an infinite loop is created, and the socket (client) keeps connecting/disconnecting. 

Not sure if this helps, but I had no such problems when using socket without this lib. [[See here](https://github.com/nickojs/zombie-survival-network-backend/blob/master/src/socket/index.ts)] It works but its not maintainable and looks really confusing.

I've just pushed a new branch with my current configurations for socket-controllers, maybe I'm doing something wrong on the integration. [[See here](https://github.com/nickojs/zombie-survival-network-backend/tree/socketControllers/src)]

And here is the [React App repository](https://github.com/nickojs/zombie-survival-network)

**Comment by NoNameProvided** [comment]
You are using socket.io 3.x while the lib is written for 2.x., This may be a reason why it's not working.

**Comment by nickojs** [comment]
@NoNameProvided 

I adjusted my project to use socket 2.x and it worked like a charm. Thanks for your explanation!
