### ISSUE TITLE
question: socket.io 3.0 support planned ?

### ISSUE THREAD

**Issue by noxz-dev** [typestack/socket-controllers#225]
Hi, is socket.io 3.0 support planned ?

**Comment by NoNameProvided** [comment]
There are quite a few breaking changes in Socket.io 3.x which makes it a non-trivial change. I certainly won't update it as I don't use this lib. Either you, @rustamwin, or someone else takes a crack at it.

**Comment by attilaorosz** [comment]
Socket.io v4 should be supported now.
