### ISSUE TITLE
NamespaceParam(s) accepts only numeric values

### ISSUE THREAD

**Issue by Kalhama** [typestack/socket-controllers#28]
Hi, I discovered that NspParam(s) decorators crash if param is string.

I checked the source code and I think it's most likely caused by one row in SocketControllerExecutor.ts.

In function parseParamValue:
```ts
            const parseValue = typeof value === "string" ? JSON.parse(value) : value;
```

should be instead
```ts
            const parseValue = typeof value !== "string" ? JSON.parse(value) : value;
```

**Comment by Kalhama** [comment]
https://github.com/typestack/socket-controllers/pull/29

**Comment by Kalhama** [comment]
https://github.com/typestack/socket-controllers/pull/29

**Comment by NoNameProvided** [comment]
The proposed solution is invalid. That way the received payload would never be parsed as JSON even if it's a JSON string.

**Comment by attilaorosz** [comment]
Should be fixed in the latest release
