### ISSUE TITLE
fix: using the @ConnectedSocket() decorator causes TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by maxloo2** [typestack/socket-controllers#574]
### Description
As the title suggests, using the @ConnectedSocket() decorator causeTypeError: Cannot read properties of undefined (reading '0'), I followed the instructions on the README to install and implement socket-controllers and with the example code I am receiving this error. Removing @ConnectedSocket() from the MessageController.ts does allow me to run without errors.

**Minimal code-snippet showcasing the problem**

```ts
  @OnConnect()
  connection(@ConnectedSocket() socket: any) {
    console.log('client connected');
  }
```

### Expected behavior
Nothing should happen.

### Actual behavior
Got "TypeError: Cannot read properties of undefined (reading '0')"

**Comment by attilaorosz** [comment]
@maxloo2 what typescript version are you using?

**Comment by attilaorosz** [comment]
@maxloo2 could you please provide a minimal repo for reproduction? I cannot reproduce this.

**Comment by maxloo2** [comment]
I also found this from some time ago: https://github.com/typestack/socket-controllers/issues/134,

**Comment by attilaorosz** [comment]
@maxloo2 Did you import reflect-metadata?

**Comment by maxloo2** [comment]
![image](https://user-images.githubusercontent.com/4709356/220338685-9b903f2c-1cab-401b-87ea-40aa4ae3bdb3.png)
@attilaorosz yes I am importing everything as instructed in the README, I have also tried with and without the es6-shim package.

**Comment by attilaorosz** [comment]
@maxloo2 I just tried the exact code (without your custom stuff) and it logs for me. Could please setup the repro repo?

**Comment by maxloo2** [comment]
@attilaorosz https://github.com/maxloo2/test. I am not sure if you can just run the files without nx but I uses this command to start nodejs: `nx run-many --target=serve`.

**Comment by maxloo2** [comment]
![image](https://user-images.githubusercontent.com/4709356/220347882-1db0c8e5-125b-49d2-b0a3-6c3051588e61.png)
![image](https://user-images.githubusercontent.com/4709356/220347939-fa5dfa7f-27c8-4207-b2f3-305a83b29966.png)

**Comment by attilaorosz** [comment]
@maxloo2 unfortunately the issue is esbuild. Since getting type definitions is a typescript thing and the guys at esbuild explicitly stated they won't support it (https://github.com/evanw/esbuild/issues/257), there is not much we can do. I suggest to choose a different bundler for nx. (https://nx.dev/packages/nx/documents/create-nx-workspace#bundler)
