### ISSUE TITLE
feat: add @Authorized() decorator

### ISSUE THREAD

**Issue by acuntex** [typestack/socket-controllers#7]
Is there any chance to create an Authorized-Decorator like in routing controllers?

Would be nice, if you could limit the connections to only authorized users (directly at connect or at message-level) and to inject the user.

**Comment by NoNameProvided** [comment]
Hi @acuntex! 

I am not familiar with the project and I don't think pleerock will have any free time soon to work on this project. However, the community can pick this up and implement and document it then it can be merged.

The first step would be to actually discuss your proposal. How do you expect the `@Authorized` decorator to work? The first message must include an authorization message or every message should contain the authorization payload?

**Comment by fr3fou** [comment]
Any news or workarounds? I'm trying to the same thing - protect some of my socket.io "routes".

**Comment by rustamwin** [comment]
@fr3fou maybe we do it, also you can use `middlewares`.

**Comment by fr3fou** [comment]
Do you have an example of the thing I'm trying to accomplish - authentication with socket.io. I'm using passport.js, routing-controllers, socket-controllers and socket.io. Right now for some reason calling `req.isAuthenticated()` gives me false for some reason.

**Comment by rustamwin** [comment]
See [sample5](https://github.com/typestack/socket-controllers/tree/master/sample/sample5-middlewares)

```typescript
@Middleware()
export class AuthenticationMiddleware implements MiddlewareInterface {

    use(socket: any, next: ((err?: any) => any)): any { // where socketio instance. not connected socket instance!
        console.log("authentication..."); // your auth logic here
        next();
    }

}
```

**Comment by fr3fou** [comment]
How would I use the middleware only for specific routes, not all

**Comment by rustamwin** [comment]
What did you mean "routes"? events?

**Comment by rustamwin** [comment]
if yes,  it is problem

**Comment by fr3fou** [comment]
Events / messages

**Comment by rustamwin** [comment]
For events no, the because middleware works globally. As I said before it is problem

**Comment by attilaorosz** [comment]
You can implement your own auth solution using interceptors per event, or use the middleware per connection.
