### ISSUE TITLE
question: Global middleware

### ISSUE THREAD

**Issue by SVR666** [typestack/socket-controllers#918]
how can i add a middleware for all the namespaces including the global? 

currently i am only able to achieve this by defining 2 middlewares

```
@Service()
@Middleware()
export class SocketGlobal implements MiddlewareInterface {
    async use(socket: Socket, _next: Function) {
       ..........  
    }
}

@Service()
@Middleware({namespace: new RegExp(".*")})
export class SocketNS implements MiddlewareInterface {
    async use(socket: Socket, _next: Function) {
       ...........
    }
}
```

Is there any simpler way to achieve this?

**Comment by attilaorosz** [comment]
This should be working out of the box if you add your middleware during the initialization phase in the middlewares array.

**Comment by attilaorosz** [comment]
I just checked the code, I was wrong, currently this is not supported. I can alter it in the next release hopefully today.

**Comment by SVR666** [comment]
> I just checked the code, I was wrong, currently this is not supported. I can alter it in the next release hopefully today.

Thank you for the quick reply.

**Comment by attilaorosz** [comment]
Should be released. Let me know if something is not correct.
