### ISSUE TITLE
fix: Missing export in Index file

### ISSUE THREAD

**Issue by SVR666** [typestack/socket-controllers#922]
### Description
There is no export available for the **OnDisconnecting decorator** in the index file.

Take a look here [index.ts:10](https://github.com/typestack/socket-controllers/blob/7cf6a41812f297c06f81680956499a6cb1def249/src/index.ts#L10)

### Expected behavior
I should be able to import this decorator.

### Actual behavior
Can't import since its not being exported in the index.

**Comment by attilaorosz** [comment]
Thanks for the report!
